baseURL = 'http://blog.noobnuby.com' 
languageCode = 'ko'
theme = "JuiceBar"
title = "ë‰´ë¹„ì˜ ê³ ìˆ˜ ì„±ì¥ë¸”ë¡œê·¸"

[params]
author = "noobnuby"
description = "My site description"
authorImage = "/images/avatar.jpg"
paginate = 5 
Title = "ì•ˆë…•í•˜ì„¸ìš”ğŸ‘‹"
content = "ë‰´ë¹„ì˜ ê³ ìˆ˜ ì„±ì¥ë¸”ë¡œê·¸!       "
imageUrl = "/images/avatar.jpg"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "Github"
url = "https://github.com/noobnuby"
[[params.social]]
name = "email"
url = "mailto:noobnuby77@gmail.com"
[[params.social]]
name = "instagram"
url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link
[[menu.main]]
name = "íƒœê·¸"
url = "/tags"
[[menu.main]]
name = "ì¹´í…Œê³ ë¦¬"
url = "/categories"
[[menu.main]]
name = "ì•„ì¹´ì´ë¸Œ"
url = "/post"

# If using the giscus commenting system
[params.giscus]
repo = "NOOBNUBY/Blog"
repoID = "R_kgDOJunxyQ"
category = "General"
categoryID = "DIC_kwDOJunxyc4CXK1d"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "ko"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]